---
- name: install docker
  dnf:
    name: docker

- name: pip packages
  pip:
    name: docker

- name: run watchtower container
  docker_container:
    name: watchtower-autoupdate
    image: #where to get it 
    restart_policy: unless-stopped
    state: stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

- name: run portainer container
  docker_container:
    name: portainer-zaza
    image: portainer/portainer
    pull: yes
    state: started
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data portainer/portainer
